on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          echo "build"
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: |
          echo "check"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          echo "running test"
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shell script
        run: sh ./hello.sh


